### ISSUE TITLE
@expo/fingerprint sample

### ISSUE THREAD

**Issue by oftoapp** [expo/UpdatesAPIDemo#11]
I'm basing it on your demo, and I see you have upgraded to expo 50 🥳

would you know how to check if build is different from store? when yes, redirect user to download update on store.

I was seeing @expo/fingerprint, but I had difficulties to understand how use it on runtime.

**Comment by douglowder** [comment]
`@expo/fingerprint` CLI is actually intended for use by the developer, to see if they have made application changes that require a new native build. The CLI and API are described [here](https://github.com/expo/expo/tree/main/packages/%40expo/fingerprint#readme).

I think `build is different from store` is something that is handled by the Apple App Store or Google Play Store, not by the app itself. If you are asking about over the air updates (EAS Update), that is handled by the JS API demonstrated in this repo.

**Comment by oftoapp** [comment]
Thank you man!

yes, this repo help me a lot to implement expo 50 changes.

but I don't know if is possible I get Native buildID from current installed app and compare with incoming Native buildID from EAS Updates

**Comment by oftoapp** [comment]
if different, I could redirect user to google play / app store.
